---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022 #optional
    volumes:
      - /srv/home_automation/radarr/data:/config
      - /media/data/movies:/movies
      - /media/data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EUROPE/BERLINE
      - UMASK_SET=022
    volumes:
      - /srv/home_automation/sonarr/data:/config
      - /media/data/tvseries:/tv
      - /media/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run options here #optional
    volumes:
      - /srv/home_automation/jackett/config:/config
      - /srv/home_automation/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/home_automation/deluge/config:/config
      - /media/data/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /srv/home_automation/plex/config:/config
      - /media/data/tvseries:/tv
      - /media/data/movies:/movies
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - BASE_URL=/ombi #optional
    volumes:
      - /srv/home_automation/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London
    ports:
      - 8191:8191
    restart: unless-stopped
